# Generated by Django 5.1.4 on 2026-05-12 01:09

import apps.attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('object_id', models.UUIDField(verbose_name='ID do objeto')),
                ('file', models.FileField(upload_to=apps.attachments.models.attachment_upload_path, verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome original')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type')),
                ('attachment_type', models.CharField(choices=[('image', 'Imagem'), ('pdf', 'PDF'), ('document', 'Documento'), ('spreadsheet', 'Planilha'), ('other', 'Outro')], db_index=True, default='image', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(blank=True, default='', help_text='Descrição opcional do anexo', max_length=200, verbose_name='Título')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='attachments/thumbnails/%Y/%m/', verbose_name='Thumbnail')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx'), models.Index(fields=['attachment_type'], name='attachments_attachm_9b35f8_idx'), models.Index(fields=['uploaded_by'], name='attachments_uploade_220573_idx')],
            },
        ),
    ]
