# Generated by Django 5.1.4 on 2026-05-12 01:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_initial'),
        ('logistics', '0002_initial'),
        ('operations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='logistics.driver', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='advance',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='operations.harvest', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='advance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='linked_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='advance',
            name='financial_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='finance.financialaccount', verbose_name='Conta financeira'),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.driver', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='financial_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.financialaccount', verbose_name='Conta financeira'),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='harvest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.harvest', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalfinancialaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialaccount',
            name='linked_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalfinancialaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalledgerentry',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.financialaccount', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='historicalledgerentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalledgerentry',
            name='source_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalledgerentry',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.financialaccount', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsettlement',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financialaccount', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reversal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_entry', to='finance.ledgerentry', verbose_name='Entrada de estorno'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalledgerentry',
            name='reversal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.ledgerentry', verbose_name='Entrada de estorno'),
        ),
        migrations.AddField(
            model_name='historicaladvance',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.ledgerentry', verbose_name='Lançamento contábil'),
        ),
        migrations.AddField(
            model_name='advance',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance', to='finance.ledgerentry', verbose_name='Lançamento contábil'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.financialaccount', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.settlement', verbose_name='Fechamento'),
        ),
        migrations.AddField(
            model_name='historicalledgerentry',
            name='settlement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.settlement', verbose_name='Fechamento'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['tenant', 'driver', 'status'], name='finance_adv_tenant__0272d1_idx'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['tenant', 'payment_date'], name='finance_adv_tenant__f8c001_idx'),
        ),
        migrations.AddConstraint(
            model_name='advance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='advance_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['account', 'status'], name='finance_set_account_904798_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['period_start', 'period_end'], name='finance_set_period__fa80f6_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status'], name='finance_set_status_bdc463_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='settlement_period_end_gte_start'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'direction', 'competence_date'], name='finance_led_account_ed341f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'entry_type'], name='finance_led_account_a6df32_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['settlement'], name='finance_led_settlem_4c6b20_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['source_type', 'source_id'], name='finance_led_source__fe5a16_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['competence_date'], name='finance_led_compete_8f842d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ledger_amount_non_negative'),
        ),
    ]
