# Generated by Django 5.1.4 on 2026-05-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_settlement_paid_overrides'),
        ('logistics', '0004_remove_fueling_fueling_price_positive_and_more'),
        ('operations', '0003_rename_operations__region_tenant_name_idx_operations__tenant__c72b7e_idx_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance', to='finance.ledgerentry', verbose_name='Lançamento no ledger'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='payment_date',
            field=models.DateField(db_index=True, verbose_name='Data do pagamento'),
        ),
        migrations.AlterField(
            model_name='advance',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código / comprovante'),
        ),
        migrations.AlterField(
            model_name='historicaladvance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='historicaladvance',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.ledgerentry', verbose_name='Lançamento no ledger'),
        ),
        migrations.AlterField(
            model_name='historicaladvance',
            name='payment_date',
            field=models.DateField(db_index=True, verbose_name='Data do pagamento'),
        ),
        migrations.AlterField(
            model_name='historicaladvance',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código / comprovante'),
        ),
        migrations.AlterField(
            model_name='historicalledgerentry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantidade (kg/ton)'),
        ),
        migrations.AlterField(
            model_name='historicalsettlement',
            name='custom_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Sobreposições manuais de valores: romaneios com carga parcial paga como cheia, descontos negociados, créditos extras, etc.', verbose_name='Ajustes manuais'),
        ),
        migrations.AlterField(
            model_name='historicalsettlement',
            name='payment_notes',
            field=models.TextField(blank=True, default='', help_text='PIX, número do comprovante, negociação realizada, etc.', verbose_name='Observações do pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalsettlement',
            name='payment_proof',
            field=models.TextField(blank=True, help_text='Foto do comprovante PIX, carta de quitação, etc.', max_length=100, null=True, verbose_name='Comprovante de pagamento'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Quantidade (kg/ton)'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='custom_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Sobreposições manuais de valores: romaneios com carga parcial paga como cheia, descontos negociados, créditos extras, etc.', verbose_name='Ajustes manuais'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='payment_notes',
            field=models.TextField(blank=True, default='', help_text='PIX, número do comprovante, negociação realizada, etc.', verbose_name='Observações do pagamento'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Foto do comprovante PIX, carta de quitação, etc.', null=True, upload_to='settlements/comprovantes/%Y/%m/', verbose_name='Comprovante de pagamento'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['tenant', 'harvest'], name='finance_adv_tenant__e22d66_idx'),
        ),
    ]
