# Generated by Django 5.1.4 on 2026-05-12 01:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da empresa')),
                ('slug', models.SlugField(help_text='Usado na URL. Ex: fazenda-sao-jose', max_length=100, verbose_name='Identificador único')),
                ('document', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ / CPF')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('starter', 'Starter'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20, verbose_name='Plano')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado'), ('trial', 'Período de teste')], db_index=True, default='trial', max_length=20, verbose_name='Status')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso horário')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período de teste')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de usuários')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa / Fazenda',
                'verbose_name_plural': 'historical Empresas / Fazendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da empresa')),
                ('slug', models.SlugField(help_text='Usado na URL. Ex: fazenda-sao-jose', max_length=100, unique=True, verbose_name='Identificador único')),
                ('document', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ / CPF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/%Y/', verbose_name='Logo')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('starter', 'Starter'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20, verbose_name='Plano')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado'), ('trial', 'Período de teste')], db_index=True, default='trial', max_length=20, verbose_name='Status')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso horário')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período de teste')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de usuários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa / Fazenda',
                'verbose_name_plural': 'Empresas / Fazendas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['status', 'is_active'], name='tenants_ten_status_d181b1_idx')],
            },
        ),
    ]
