# Generated by Django 5.1.4 on 2026-05-12 01:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('document_cpf', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF')),
                ('document_cnh', models.CharField(blank=True, default='', max_length=20, verbose_name='CNH')),
                ('cnh_category', models.CharField(blank=True, default='', max_length=5, verbose_name='Categoria CNH')),
                ('cnh_expiry', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('on_leave', 'Em afastamento')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Motorista',
                'verbose_name_plural': 'historical Motoristas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFueling',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('fueling_date', models.DateField(db_index=True, verbose_name='Data')),
                ('fuel_type', models.CharField(choices=[('diesel_s10', 'Diesel S10'), ('diesel_s500', 'Diesel S500'), ('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('arla', 'ARLA 32')], default='diesel_s10', max_length=20, verbose_name='Tipo combustível')),
                ('liters', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Litros')),
                ('price_per_liter', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Preço por litro (R$)')),
                ('payment_method', models.CharField(choices=[('driver_account', 'Débito na conta do motorista'), ('company', 'Empresa (sem desconto)'), ('cash', 'Dinheiro')], default='driver_account', max_length=20, verbose_name='Forma de pagamento')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hodômetro (km)')),
                ('station_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Posto / Local')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Abastecimento',
                'verbose_name_plural': 'historical Abastecimentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('plate', models.CharField(db_index=True, max_length=10, verbose_name='Placa')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Caminhão simples'), ('semi_trailer', 'Carreta/Bitrem'), ('tractor', 'Trator'), ('pickup', 'Camionete'), ('other', 'Outro')], default='truck', max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('maintenance', 'Em manutenção'), ('inactive', 'Inativo')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('payload_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade de carga (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Veículo',
                'verbose_name_plural': 'historical Veículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('plate', models.CharField(db_index=True, max_length=10, verbose_name='Placa')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Caminhão simples'), ('semi_trailer', 'Carreta/Bitrem'), ('tractor', 'Trator'), ('pickup', 'Camionete'), ('other', 'Outro')], default='truck', max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('maintenance', 'Em manutenção'), ('inactive', 'Inativo')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('payload_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade de carga (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nome')),
                ('document_cpf', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF')),
                ('document_cnh', models.CharField(blank=True, default='', max_length=20, verbose_name='CNH')),
                ('cnh_category', models.CharField(blank=True, default='', max_length=5, verbose_name='Categoria CNH')),
                ('cnh_expiry', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('on_leave', 'Em afastamento')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/%Y/%m/', verbose_name='Foto')),
                ('financial_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='finance.financialaccount', verbose_name='Conta financeira')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('fueling_date', models.DateField(db_index=True, verbose_name='Data')),
                ('fuel_type', models.CharField(choices=[('diesel_s10', 'Diesel S10'), ('diesel_s500', 'Diesel S500'), ('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('arla', 'ARLA 32')], default='diesel_s10', max_length=20, verbose_name='Tipo combustível')),
                ('liters', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Litros')),
                ('price_per_liter', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Preço por litro (R$)')),
                ('payment_method', models.CharField(choices=[('driver_account', 'Débito na conta do motorista'), ('company', 'Empresa (sem desconto)'), ('cash', 'Dinheiro')], default='driver_account', max_length=20, verbose_name='Forma de pagamento')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hodômetro (km)')),
                ('station_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Posto / Local')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuelings', to='logistics.driver', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-fueling_date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
