# Generated by Django 5.1.4 on 2026-05-12 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('logistics', '0001_initial'),
        ('operations', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuelings', to='operations.harvest', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fueling', to='finance.ledgerentry', verbose_name='Entrada no ledger'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='financial_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.financialaccount', verbose_name='Conta financeira'),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldriver',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalfueling',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.driver', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='historicalfueling',
            name='harvest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.harvest', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='historicalfueling',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfueling',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.ledgerentry', verbose_name='Entrada no ledger'),
        ),
        migrations.AddField(
            model_name='historicalfueling',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='default_driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.driver', verbose_name='Motorista padrão'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='default_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vehicles', to='logistics.driver', verbose_name='Motorista padrão'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalfueling',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.vehicle', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='fueling',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuelings', to='logistics.vehicle', verbose_name='Veículo'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['tenant', 'status'], name='logistics_d_tenant__bc9a87_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['name'], name='logistics_d_name_5a8f92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('tenant', 'plate')},
        ),
        migrations.AddIndex(
            model_name='fueling',
            index=models.Index(fields=['driver', 'fueling_date'], name='logistics_f_driver__e1b0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='fueling',
            index=models.Index(fields=['vehicle', 'fueling_date'], name='logistics_f_vehicle_96bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='fueling',
            index=models.Index(fields=['harvest'], name='logistics_f_harvest_10dfed_idx'),
        ),
        migrations.AddIndex(
            model_name='fueling',
            index=models.Index(fields=['payment_method'], name='logistics_f_payment_200755_idx'),
        ),
        migrations.AddConstraint(
            model_name='fueling',
            constraint=models.CheckConstraint(condition=models.Q(('liters__gt', 0)), name='fueling_liters_positive'),
        ),
        migrations.AddConstraint(
            model_name='fueling',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_liter__gt', 0)), name='fueling_price_positive'),
        ),
    ]
