# Generated by Django 5.1.4 on 2026-05-28 06:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_proprietario_vehicle_fueling_dual_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fueling',
            name='fueling_price_positive',
        ),
        migrations.RenameIndex(
            model_name='proprietario',
            new_name='logistics_p_tenant__9a5a30_idx',
            old_name='logistics_proprietario_tenant_name_idx',
        ),
        migrations.AlterField(
            model_name='historicalfueling',
            name='extras_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor total de outros produtos comprados no mesmo cupom (ex.: ARLA 32, lubrificantes).', max_digits=10, verbose_name='Outros produtos no cupom (R$)'),
        ),
        migrations.AlterField(
            model_name='historicalfueling',
            name='posted_price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valor real cobrado pelo posto. Deixe em branco se igual ao desconto.', max_digits=8, null=True, verbose_name='Preço do posto (R$/L)'),
        ),
    ]
