# Generated by Django 5.1.4 on 2026-05-12 01:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('logistics', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('crop_type', models.CharField(choices=[('soybean', 'Soja'), ('corn', 'Milho'), ('cotton', 'Algodão'), ('sugarcane', 'Cana-de-açúcar'), ('coffee', 'Café'), ('rice', 'Arroz'), ('wheat', 'Trigo'), ('other', 'Outro')], default='soybean', max_length=20, verbose_name='Cultura principal')),
                ('status', models.CharField(choices=[('planning', 'Em planejamento'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='planning', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('expected_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área esperada (ha)')),
                ('expected_yield_ton_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Produtividade esperada (ton/ha)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do talhão')),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (ha)')),
                ('location_description', models.CharField(blank=True, max_length=300, verbose_name='Localização / Referência')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='operations.harvest', verbose_name='Safra')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalField',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do talhão')),
                ('area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (ha)')),
                ('location_description', models.CharField(blank=True, max_length=300, verbose_name='Localização / Referência')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('harvest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.harvest', verbose_name='Safra')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'historical Talhão',
                'verbose_name_plural': 'historical Talhões',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHarvest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('crop_type', models.CharField(choices=[('soybean', 'Soja'), ('corn', 'Milho'), ('cotton', 'Algodão'), ('sugarcane', 'Cana-de-açúcar'), ('coffee', 'Café'), ('rice', 'Arroz'), ('wheat', 'Trigo'), ('other', 'Outro')], default='soybean', max_length=20, verbose_name='Cultura principal')),
                ('status', models.CharField(choices=[('planning', 'Em planejamento'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='planning', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('expected_area_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área esperada (ha)')),
                ('expected_yield_ton_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Produtividade esperada (ton/ha)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'historical Safra',
                'verbose_name_plural': 'historical Safras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWaybill',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('number', models.PositiveIntegerField(db_index=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('settled', 'Fechado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Data da operação')),
                ('operation_time', models.TimeField(blank=True, null=True, verbose_name='Hora da operação')),
                ('culture', models.CharField(choices=[('soybean', 'Soja'), ('corn', 'Milho'), ('cotton', 'Algodão'), ('sugarcane', 'Cana-de-açúcar'), ('coffee', 'Café'), ('rice', 'Arroz'), ('wheat', 'Trigo'), ('other', 'Outro')], default='soybean', max_length=20, verbose_name='Cultura')),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso bruto (kg)')),
                ('tare_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Tara (kg)')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Valor pago por tonelada transportada', max_digits=10, verbose_name='Preço por tonelada (R$)')),
                ('destination', models.CharField(blank=True, default='', max_length=200, verbose_name='Destino / Armazém')),
                ('scale_ticket', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Ticket balança')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.driver', verbose_name='Motorista')),
                ('field', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.field', verbose_name='Talhão')),
                ('harvest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.harvest', verbose_name='Safra')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.ledgerentry', verbose_name='Entrada no ledger')),
                ('settlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.settlement', verbose_name='Fechamento')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant', verbose_name='Empresa')),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'historical Romaneio',
                'verbose_name_plural': 'historical Romaneios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('number', models.PositiveIntegerField(db_index=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('settled', 'Fechado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('operation_date', models.DateField(db_index=True, verbose_name='Data da operação')),
                ('operation_time', models.TimeField(blank=True, null=True, verbose_name='Hora da operação')),
                ('culture', models.CharField(choices=[('soybean', 'Soja'), ('corn', 'Milho'), ('cotton', 'Algodão'), ('sugarcane', 'Cana-de-açúcar'), ('coffee', 'Café'), ('rice', 'Arroz'), ('wheat', 'Trigo'), ('other', 'Outro')], default='soybean', max_length=20, verbose_name='Cultura')),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso bruto (kg)')),
                ('tare_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Tara (kg)')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Valor pago por tonelada transportada', max_digits=10, verbose_name='Preço por tonelada (R$)')),
                ('destination', models.CharField(blank=True, default='', max_length=200, verbose_name='Destino / Armazém')),
                ('scale_ticket', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Ticket balança')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='logistics.driver', verbose_name='Motorista')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='operations.field', verbose_name='Talhão')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='operations.harvest', verbose_name='Safra')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='finance.ledgerentry', verbose_name='Entrada no ledger')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='finance.settlement', verbose_name='Fechamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Empresa')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waybills', to='logistics.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Romaneio',
                'verbose_name_plural': 'Romaneios',
                'ordering': ['-operation_date', '-number'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['tenant', 'status'], name='operations__tenant__f5f476_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['tenant', 'start_date'], name='operations__tenant__142511_idx'),
        ),
        migrations.AddConstraint(
            model_name='harvest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant',), name='unique_active_harvest_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['tenant', 'harvest'], name='operations__tenant__d59c3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('tenant', 'harvest', 'name')},
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['tenant', 'number'], name='operations__tenant__4def69_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['harvest', 'status'], name='operations__harvest_0367be_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['driver', 'operation_date'], name='operations__driver__0a810b_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['operation_date'], name='operations__operati_86285f_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['settlement'], name='operations__settlem_17b82b_idx'),
        ),
        migrations.AddConstraint(
            model_name='waybill',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='waybill_unique_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='waybill',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gt', 0)), name='waybill_gross_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='waybill',
            constraint=models.CheckConstraint(condition=models.Q(('tare_weight__gte', 0)), name='waybill_tare_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='waybill',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='waybill_unit_price_positive'),
        ),
    ]
